[package]
name = "mysql-cli"
version = "0.1.0"
authors = ["kawabata_shintaro <4499135+kawabatas@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "20.1.0"
dotenv = "0.15.0"
